
services:
  backend:
    build:
      context: ./server
    container_name: backend
    env_file:
      - ./server/.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: "3306"
      DB_DATABASE: mochi
      DB_USERNAME: appuser
      DB_PASSWORD: StrongPass!123
      DB_AUTO_IMPORT: ${DB_AUTO_IMPORT:-false}
      TZ: Asia/Bangkok
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server/app:/var/www/html/app
      - ./server/routes:/var/www/html/routes
      - ./server/resources:/var/www/html/resources
      - ./server/database:/var/www/html/database
      - ./data:/var/www/html/data
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage
    ports:
      - "8005:8080"   # Backend: http://localhost:8005
    networks:
      - webnet
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: client
    depends_on:
      - backend
    ports:
      - "3005:80"   # Frontend: http://localhost:3005
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  webnet:
    driver: bridge

volumes:
  vendor_data:
  storage_data:
