server {
  listen 80;
  server_name _;

  # Sử dụng Docker internal DNS để phân giải tên miền động, tránh lỗi crash Nginx khi boot
  resolver 127.0.0.11 valid=30s;

  root /var/www/html/public;
  index index.php index.html;

  # Static nhanh
  location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp|woff2?)$ {
    access_log off;
    expires 1h;
    add_header Cache-Control "public";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include fastcgi_params;
    
    # Gán biến để Nginx phân giải IP lúc runtime thay vì lúc khởi động
    set $upstream_fpm api-fpm:9000;
    fastcgi_pass $upstream_fpm;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_read_timeout 300;
    fastcgi_buffering on;
  }

  client_max_body_size 20m;
}
